// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-06VtiFotIBIZ7LrKSaf2muN49kF5XS0',
    appId: '1:630014730541:web:f05eb5751d2f50eeea73a4',
    messagingSenderId: '630014730541',
    projectId: 'basicstudentinfo',
    authDomain: 'basicstudentinfo.firebaseapp.com',
    storageBucket: 'basicstudentinfo.appspot.com',
    measurementId: 'G-P0QFQ06236',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAESCmPt3bEjBtpWtCvoiI_pyMA9aCQ-uE',
    appId: '1:630014730541:android:40e5ad0dab97d729ea73a4',
    messagingSenderId: '630014730541',
    projectId: 'basicstudentinfo',
    storageBucket: 'basicstudentinfo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_kAumhsGc2CE1H80N15N1mCGJEwypAAs',
    appId: '1:630014730541:ios:be934a2c026748caea73a4',
    messagingSenderId: '630014730541',
    projectId: 'basicstudentinfo',
    storageBucket: 'basicstudentinfo.appspot.com',
    iosBundleId: 'com.example.practice1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-06VtiFotIBIZ7LrKSaf2muN49kF5XS0',
    appId: '1:630014730541:web:71e98440147dd50aea73a4',
    messagingSenderId: '630014730541',
    projectId: 'basicstudentinfo',
    authDomain: 'basicstudentinfo.firebaseapp.com',
    storageBucket: 'basicstudentinfo.appspot.com',
    measurementId: 'G-CL91MBTM1N',
  );
}
